server:
  port: 8082
spring:  ## 数据源的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    # url: jdbc:mysql://94.191.43.232:3306/dingding?useSSL=false&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/xmgl?useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 10                               # 初始化提供的连接数
      max-total: 20                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml         # 默认去src/main/resources 扫描
  type-aliases-package: com.gedi.projectmanagement.model       # 实体类别名
mapper:
  mappers:
    - com.gedi.projectmanagement.base.GeneralMapper
  not-empty: false
  identity: MYSQL

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# logger level
logging:
  level:
    com.gedi.projectmanagement: DEBUG