server:
  port: 8082
spring:  ## 数据源的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/xmgl?allowMultiQueries=true
    password: 123456
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mybatis:
  mapper-locations: classpath:mapper/*.xml         # 默认去src/main/resources 扫描
  type-aliases-package: com.gedi.projectmanagement.model       # 实体类别名

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# mybatis 显示sql
logging:
  level:
    com.gedi.projectmanagement.dao: DEBUG